# Generated by Django 4.0.5 on 2023-08-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_remove_contact_facebook_remove_contact_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_avatar1',
            field=models.FileField(blank=True, null=True, upload_to='about_abatar1'),
        ),
        migrations.AddField(
            model_name='about',
            name='about_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
