# Generated by Django 4.0.5 on 2023-08-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_about_about_avatar1_about_about_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='avtar',
            field=models.FileField(blank=True, null=True, upload_to='avtar'),
        ),
    ]
