# Generated by Django 4.0.5 on 2023-08-23 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0018_personalinformation_avtar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='num',
            new_name='percent',
        ),
    ]
