# Generated by Django 4.0.5 on 2023-08-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0020_rename_skill_projects_tech'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements', models.CharField(blank=True, max_length=250, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, max_length=50, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_avatar1',
        ),
        migrations.AlterField(
            model_name='about',
            name='about_avatar',
            field=models.FileField(blank=True, null=True, upload_to='about_avatar'),
        ),
    ]
