# Generated by Django 4.0.5 on 2023-08-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0021_achievements_remove_about_about_avatar1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='achievements',
            new_name='achievement',
        ),
    ]
