# Generated by Django 4.0.5 on 2024-08-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0022_rename_achievements_achievements_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='profile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
