# Generated by Django 4.0.5 on 2024-08-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0023_personalinformation_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='image',
            new_name='avatar_link',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='link',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='location',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_avatar',
            field=models.FileField(blank=True, null=True, upload_to='contact_avatar'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
