# Generated by Django 4.0.5 on 2024-08-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0024_rename_image_contact_avatar_link_remove_contact_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_img',
            new_name='avatar_link',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='avatar',
            new_name='avatar_link',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='mycv',
            new_name='resume_link',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='avtar',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='cv',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='profile_avatar',
            field=models.FileField(blank=True, null=True, upload_to='profile_avatar'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
    ]
