# Generated by Django 4.0.5 on 2024-08-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0025_rename_about_img_about_avatar_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
