# Generated by Django 4.0.5 on 2024-08-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0026_personalinformation_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='mini_about',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='personalinformation',
            old_name='name_complete',
            new_name='name',
        ),
    ]
